### ISSUE TITLE
Pendulum Summon

### ISSUE THREAD

**Issue by kharism** [ProjectIgnis/windbot#21]
Hi I've been trying to build a zefra bot. But I can't seems figure out how to pendulum summon.
Ive add 
`public override IList<ClientCard> OnSelectPendulumSummon(IList<ClientCard> cards, int max)`

and 
`AddExecutor(ExecutorType.SpSummon);` 
on ControlExecutor but it seems I can't get to pendulum summon.

**Comment by kevinlul** [comment]
Where are you placing the `AddExecutor` call? The order matters as the executors added first will be used first.

**Comment by kharism** [comment]
This is My MainExecutor
`public ZefraControlExecutor(GameAI ai, Duel duel) : base(ai, duel)
        {
            
            // counter
            AddExecutor(ExecutorType.Activate, CardId.PsyFrameGamma, GammaEffect);
            AddExecutor(ExecutorType.Activate, CardId.EffectVeiler, DefaultEffectVeiler);
            AddExecutor(ExecutorType.Activate, CardId.AshBlossom, DefaultAshBlossomAndJoyousSpring);
            AddExecutor(ExecutorType.Activate, CardId.GhostOgre, DefaultGhostOgreAndSnowRabbit);

            //search field spell
            AddExecutor(ExecutorType.Activate, CardId.Terraforming, TerraformingEffect);
            AddExecutor(ExecutorType.Activate, CardId.ZefraProvidence, ZefraProvidence);

            // try to complete our scale
            AddExecutor(ExecutorType.Activate, CardId.OracleZefra, OracleActivate);
            AddExecutor(ExecutorType.Activate, CardId.Zefraath, ZefraathActivate);
            AddExecutor(ExecutorType.Activate, CardId.Zefraath, ZefraathDump);
            AddExecutor(ExecutorType.Activate, CardId.Zefraniu, ZefraniuSearch);

            // putting low scale prioritize non zefraxi card
            AddExecutor(ExecutorType.Activate, CardId.Zefrathuban);
            AddExecutor(ExecutorType.Activate, CardId.Zefraxi);
            AddExecutor(ExecutorType.SpSummon);
            //AddExecutor(ExecutorType.SpSummon,CardId.Crocodragon,SynchroCrocodragon);

            //AddExecutor(ExecutorType.Activate, CardId.Zefraath, ZefraathActivate);

        }`
``
`public override IList<ClientCard> OnSelectPendulumSummon(IList<ClientCard> cards, int max)
        {
            Logger.DebugWriteLine("OnSelectPendulumSummon");
            IList<ClientCard> selected = new List<ClientCard>();
            for (int i = 1; i <= max; ++i)
            {
                
                ClientCard card = cards[cards.Count - i];
                if (card.IsCode(CardId.Zefraniu)||card.IsCode(CardId.Zefraxi)) {
                    selected.Add(card);
                    continue; 
                }
            }
            if (selected.Count == 0)
            selected.Add(cards[cards.Count - 1]);
            return selected;
        }`

From my own debugging in the GameAI.cs this line
`if (hint == HINTMSG_SPSUMMON && min == 1 && max > min)`
is never executed for some reason, max & min is 1 when I tried to pendulum summon. So the above code only summon zefraxi from hand but not summoning zefraniu from extra deck.

**Comment by kharism** [comment]
Okay I've found a solution by overriding OnSelectCard method. Not sure why this is the case.

**Comment by kevinlul** [comment]
Hopefully you're interested in submitting pull requests for your executors if they work so the community can also enjoy them!

**Comment by kharism** [comment]
I will. It just won't be as good as the altergeist executor. That things just crazy complex. Will the executor backward compatible with IceYGO? or need some minor modification?

I just find the OnSelectPendulumSummon method does not working as intended.
