### ISSUE TITLE
Crocodragon ActivateDescription is always 0

### ISSUE THREAD

**Issue by kharism** [ProjectIgnis/windbot#22]
Crocodragon has 2 effect, 1st effect is trigger effect, draw on synchro summon, 2nd is discard 2 to target and destroy a card on the field.
I have this code to check what effect would activate

> private bool CrocoDragonTrigger() {
            if (ActivateDescription == Util.GetStringId(CardId.Crocodragon, 0)) {
                return true;
            }
            return false;
        }

in that code ActivateDescription for some reason always have 0 value

**Comment by edo9300** [comment]
That value is 0 because the script doesn't have descriptions for the effects

**Comment by edo9300** [comment]
Also, you're checking the wrong, give a look at the executor of Dragon Spirit of White in BlueEyesExecutor, that as well has to check between a trigger effect and a quick effect (the same scenario of croco dragon)

**Comment by NaimSantos** [comment]
Strings added in https://github.com/ProjectIgnis/CardScripts/commit/9c2190f9706ace22f285021bcfed8199065f7acd and https://github.com/ProjectIgnis/CardScripts/commit/9c2190f9706ace22f285021bcfed8199065f7acd

**Comment by kharism** [comment]
Its resolved now, thanks
