### ISSUE TITLE
AI decks will not play with rulesets and yet are also uneditable.

### ISSUE THREAD

**Issue by ThatGuySittin** [ProjectIgnis/windbot#26]
Is there any timeline on possibly making AI decks editable? Every deck seems to have some card or amount thereof that makes it unplayable against decks that want to abide by banlists. Really limits the functionality. And I am more than willing to customize the decks, but that isn't possible either. I tried manually removing cards from the decks .ydk files but when i do it simply stops playing the deck altogether.

**Comment by NaimSantos** [comment]
Each AI deck is programmed to work with a certain set of cards. If you want to 'edit' it, you have to rewrite the code that tells the AI how to use the deck, to reflect the changes you did to the deck file. In other words, you need to program. Just removing/adding cards from the file doesn't make it magically learn how to use/behave with/without those.

**Comment by ThatGuySittin** [comment]
Then I will do that. I am aware of how code functions. I don't believe it magically works. I assumed that, as I read in other blogs for other ygo simulators, that the decks were editable, there just wasn't a GUI option yet. Also that was my original question in this post. It was not to be condescendingly reminded how code works. A script does not have to be limited in this way. And so it isn't good faith to assume that it is. Thank you for your time.

**Comment by kevinlul** [comment]
Your question was answered. To edit a deck the way you want, the code for the corresponding executor must be changed to account. It seems like you tried to drop cards from a deck list, but that would likely make the deck invalid outright.
