### ISSUE TITLE
Can't create an AI that flip summons

### ISSUE THREAD

**Issue by Grimmr** [ProjectIgnis/windbot#37]
The windbot backend doesn't seem to be capable of flip summoning monsters. I havn't found an Executor that will flip a monster set by book of moon back up. I also can't find where in the source an executor would choose to flip summon a monster. 

I realise this isn't supper common in modern yu-gi-oh but it means that the ai can't choose to resolve a flip effect without resolving a card that flips it face up for me. Also it means that cards which only have effects on flip summon (not on flip) (eg Des Lacooda) can't be triggered.

Is this intentional?

I apologise if I've missed something and would be happy to implement this myself if you could point me to where in the codebase windbot sends it's decisions back to the duel host.

Thanks for your time.

**Comment by that-hatter** [comment]
I'm fairly sure it's possible with the `Repos` executor type.

> I havn't found an Executor that will flip a monster set by book of moon back up. I also can't find where in the source an executor would choose to flip summon a monster.

afaik almost all the current ones will flip their monsters face-up as much as they can before proceeding to battle. They use `Repos` for that (otherwise, most monsters would just be stuck face-down for the whole game).

**Comment by Grimmr** [comment]
I'll give this a try. There's quite a few executors bundled with this version of windbot so maybe I just got unlucky with the ones I tested.

Thanks for your help I'll mark this as closed after I give it a go this afternoon

**Comment by Grimmr** [comment]
> I'm fairly sure it's possible with the Repos executor type.

This is correct. Thanks for helping out so quickly
